version: '3'

services:
  db:
    container_name: db 
    hostname: host.docker.internal 
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=afyfncshrjd228
      - POSTGRES_DB=postgres
    ports: 
      - "5432:5432"

  server:
    restart: always
    container_name: server
    build: ./
    ports: 
      - "4000:4000"
    links: 
      - db  
